# Generated by Django 3.1.6 on 2021-02-22 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tempo', models.TimeField()),
                ('estado', models.CharField(choices=[('A', 'Agendado'), ('E', 'Esperando'), ('C', 'Cancelado')], default='E', max_length=1)),
                ('totalAPagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preçoTotal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='AgendamentoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicoAgendam', to='agendamento.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicoAgendam', to='servicos.servico')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='agendamento.AgendamentoServico', to='servicos.Servico'),
        ),
    ]
