# Generated by Django 3.1.6 on 2021-02-23 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='tempo',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tempoASerGasto',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='tempo gasto no atendimento'),
            preserve_default=False,
        ),
    ]
