# Generated by Django 3.1.6 on 2021-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tempo',
            field=models.TimeField(verbose_name='tempo gasto no atendimento'),
        ),
    ]
