# Generated by Django 3.1.6 on 2021-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('agendamento', '0002_auto_20210222_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(null=True, through='agendamento.AgendamentoServico', to='servicos.Servico'),
        ),
    ]
