# Generated by Django 3.1.6 on 2021-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
        ('agendamento', '0003_auto_20210319_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='agendamento.AgendamentoServico', to='servicos.Servico'),
        ),
    ]
