# Generated by Django 3.1.6 on 2021-02-08 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salao',
            managers=[
                ('saloes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='servico',
            managers=[
                ('Servicos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='salao',
            name='image',
            field=models.ImageField(blank=True, upload_to='saloes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.salao'),
        ),
    ]
