# Generated by Django 3.1.6 on 2021-02-10 12:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20210208_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salao',
            options={'verbose_name': 'salão', 'verbose_name_plural': 'salões'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.salao'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
    ]
