# Generated by Django 3.1.6 on 2021-02-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0003_auto_20210210_0952'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salao',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='salao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
